name: Gesture Booth
icon: ✌️
description: Detects gesture and provide feedback to the user. Gesture Recognition Example

bricks:
  - arduino:gesture_recognition:
      model: face-detection
  - arduino:web_ui
