# See: https://taskfile.dev/#/usage
version: "3"

tasks:
  # Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/check-markdown-task/Taskfile.yml
  markdown:check-links:
    desc: Check for broken links
    vars:
      # The command is defined in a Taskfile variable to allow it to be broken into multiple lines for readability.
      # This can't be done in the `cmd` object of the Taskfile because `npx --call` uses the native shell, which causes
      # standard newline escaping syntax to not work when the task is run on Windows.
      #
      # Using -regex instead of -name to avoid Task's behavior of globbing even when quoted on Windows
      # The odd method for escaping . in the regex is required for windows compatibility because mvdan.cc/sh gives
      # \ characters special treatment on Windows in an attempt to support them as path separators.
      #
      # prettier-ignore
      CHECK_LINKS_COMMAND:
        "
          find . \
            -type d -name \".git\" -prune -o \
            -type d -name \".licenses\" -prune -o \
            -type d -name \"__pycache__\" -prune -o \
            -type d -name \"node_modules\" -prune -o \
            -regex \".*[.]md\" \
            -exec \
              markdown-link-check \
                --quiet \
                --config \"./.markdown-link-check.json\" \
                \\{\\} \
                +
        "
    cmds:
      - |
        npx \
          --package=markdown-link-check \
          --call='{{.CHECK_LINKS_COMMAND}}'
