name: Music Composer
icon: 🎵
description: A music composer app that lets you create melodies by composing notes with different durations and play them using sound generation.
bricks:
  - arduino:web_ui
  - arduino:sound_generator
