name: Air Quality Monitoring App
description: An Air Quality Monitoring System that uses air quality AQI API data to show the air quality state on the LED matrix.
icon: 🍃
bricks:
  - arduino:air_quality_monitoring