name: Face Detector on Camera
icon: ☺️
description: This example showcases face detection within a live feed from a USB camera.

bricks:
  - arduino:video_object_detection:
      model: face-detection
  - arduino:web_ui
